#!/bin/bash
rm -rf build-verif
mkdir -p build-verif


# Copy UCCA's Verilog source code to temp directory
cp ../openmsp430/msp_core/openMSP430_undefines.v ./build-verif/
cp ../openmsp430/msp_core/openMSP430_defines.v ./build-verif/

if [ "ucca" = $1 ]
then
    cp ../ucca/hw-mod-nusmv/UCCA/*.v ./build-verif/
    # Specification
    cp ../verification_specs/hwmod_specs.smv ./build-verif/ltl_specs.smv
    for filename in ./build-verif/*.v; do
	sed -i "s/always @(posedge clk)/always @(*)/g" $filename
    done

    sh ./verif-tools/verilog2smv.sh ./build-verif/hwmod.v ./build-verif/hwmod_generated.smv hwmod
elif [ "return" = $1 ]
then
    cp ../ucca/hw-mod-nusmv/return_integrity/*.v ./build-verif/
    cp ../verification_specs/return_specs.smv ./build-verif/ltl_specs.smv
    for filename in ./build-verif/*.v; do
	sed -i "s/always @(posedge clk)/always @(*)/g" $filename
    done

    sh ./verif-tools/verilog2smv.sh ./build-verif/UCCA_region.v ./build-verif/hwmod_generated.smv UCCA_region
elif [ "stack" = $1 ]
then
    cp ../ucca/hw-mod-nusmv/stack_protection/*.v ./build-verif/
    cp ../verification_specs/stack_specs.smv ./build-verif/ltl_specs.smv
    for filename in ./build-verif/*.v; do
	sed -i "s/always @(posedge clk)/always @(*)/g" $filename
    done

    sh ./verif-tools/verilog2smv.sh ./build-verif/UCCA_region.v ./build-verif/hwmod_generated.smv UCCA_region
elif [ "cr" = $1 ]
then
    cp ../ucca/hw-mod-nusmv/cr_integrity/*.v ./build-verif/
    cp ../verification_specs/cr_specs.smv ./build-verif/ltl_specs.smv
    for filename in ./build-verif/*.v; do
	sed -i "s/always @(posedge clk)/always @(*)/g" $filename
    done

    sh ./verif-tools/verilog2smv.sh ./build-verif/CR_integrity.v ./build-verif/hwmod_generated.smv CR_integrity
fi

sed -i "s/IVAR/VAR/g" ./build-verif/hwmod_generated.smv # Hacky here since IVAR doesnt work properly
echo '#include "ltl_specs.smv"' >> ./build-verif/hwmod_generated.smv

#./verif-tools/NuSMV  -v 2 -pre cpp ./build-verif/hwmod_generated.smv
#./verif-tools/NuSMV -coi -df -dcx -pre cpp ./build-verif/hwmod_generated.smv
#./verif-tools/NuSMV -i order.ord -coi -dcx -df -v 1 -pre cpp ./build-verif/hwmod_generated.smv
./verif-tools/NuSMV -coi -df -v 1 -pre cpp ./build-verif/hwmod_generated.smv
#./verif-tools/NuSMV -ctt -v 1 -pre cpp ./build-verif/hwmod_generated.smv
#./verif-tools/NuSMV -bmc -bmc_length 10 -v 1 -pre cpp ./build-verif/hwmod_generated.smv

#rm -rf build-verif
